services:
  - type: web
    name: rootai-community-portal
    env: node
    plan: free # Can be upgraded by the user based on workload
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # User will paste their key in the Render Dashboard
      - key: APP_URL
        sync: false # Automatically computed or set in the Render Dashboard
